apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "etcd-v3-browser.fullname" . }}
  labels:
    {{- include "etcd-v3-browser.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "etcd-v3-browser.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "etcd-v3-browser.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "etcd-v3-browser.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          env:
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
            {{- if .Values.etcd.hosts }}
            - name: ETCD_HOSTS
              value: {{ .Values.etcd.hosts | quote }}
            {{- end }}
            {{- if .Values.etcd.tls.enabled }}
            - name: ETCD_CA_CERT
              value: /etc/etcd-tls/{{ .Values.etcd.tls.caCertKey }}
            - name: ETCD_CLIENT_CERT
              value: /etc/etcd-tls/{{ .Values.etcd.tls.clientCertKey }}
            - name: ETCD_CLIENT_KEY
              value: /etc/etcd-tls/{{ .Values.etcd.tls.clientKeyKey }}
            {{- end }}
          {{- if .Values.etcd.tls.enabled }}
          volumeMounts:
            - name: etcd-tls
              mountPath: /etc/etcd-tls
              readOnly: true
          {{- end }}
          livenessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.etcd.tls.enabled }}
      volumes:
        - name: etcd-tls
          secret:
            secretName: {{ .Values.etcd.tls.secretName }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
